baseurl: "https://rcammisola.github.io/"
title: Home
publishDir: "docs"

theme: beautifulhugo
languageCode: en
defaultContentLanguage: en
copyright: Rocco Cammisola
disqusShortname: "rcammisola-github-io"

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    style: "dracula"

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Rocco Cammisola
  profile: ""
  github: "rcammisola"
  twitter: "rcammisola"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  homeTitle: Rocco Cammisola
  subtitle: I don't know what I'm doing, hopefully I'll work it out...
  logo: "img/profile.jpeg"
  since: 2020
  rss: false
  dateFormat: "Mon, Jan 2, 2006"
  comments: true
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Posts
      url: /
      weight: 1
    - name: About
      url: /page/about/
      weight: 2
