baseurl: "https://rcammisola.github.io/"
title: Rocco Cammisola
theme: ghostwriter
languageCode: en-gb
copyright: Rocco Cammisola
pygmentsUseClasses: true
pygmentsCodeFences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: dracula
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: My Name
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Ghostwriter example
  description: I don't know what I'm doing, hopefully I'll work it out...
  github: "https://github.com/rcammisola"
  twitter: "https://twitter.com/rcammisola"
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: false
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

# menu:
#   main:
#     - name: Blog
#       url: /
#       weight: 1
#     - name: Projects
#       url: /project/
#       weight: 2
#     - name: Contact
#       url: /page/contact/
#       weight: 3
#     - name: About
#       url: /page/about/
#       weight: 4
