baseURL = "https://rcammisola.github.io/"
languageCode = "en-gb"
title = "Rocco Cammisola"
theme = "ghostwriter"
pygmentsUseClasses = true
pygmentsCodefences = true

[markup]
  [highlight]
    codeFences= true
    guessSyntax= false
    hl_Lines= ""
    lineNoStart= 1
    lineNos= false
    lineNumbersInTable= true
    noClasses= true
    tabWidth= 2


[params]
    mainSections = ["post"]
    headline = "My headline"
    description = "I don't know what I'm doing, hopefully I'll work it out..."
    githubName = "https://www.github.com/rcammisola"
    twitterName = "https://www.twitter.com/rcammisola"
    opengraph = true
    shareTwitter = true
    hideHUGOSupport = false

[permalinks]
    post = "/:filename/"

[taxonomies]
category = "categories"
tag = "tags"
